name: Flutter iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Flutter (force fresh install with Dart 3.9.2)
      - name: Install Flutter 3.27.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: false

      # 3️⃣ Verify Flutter & Dart versions
      - name: Flutter & Dart version
        run: |
          flutter --version
          dart --version

      # 4️⃣ Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # 5️⃣ Build iOS app (no signing)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 6️⃣ Upload compiled iOS app
      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios/iphoneos/
