name: Flutter iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Remove any preinstalled Flutter versions
      - name: Remove preinstalled Flutter
        run: |
          sudo rm -rf /Users/runner/hostedtoolcache/flutter
          sudo rm -rf $HOME/flutter

      # 3️⃣ Install Flutter 3.27.3 (stable)
     - name: Install Flutter 3.27.3
        run: |
            git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
            cd $HOME/flutter
            git fetch --all --tags
            git checkout 3.27.3 || (echo "❌ Flutter 3.27.3 tag not found"; exit 1)
            echo "$HOME/flutter/bin" >> $GITHUB_PATH

      # 4️⃣ Verify installation (in a new shell so PATH is reloaded)
      - name: Verify Flutter & Dart version
        run: |
          which flutter
          flutter --version
          dart --version

      # 5️⃣ Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 6️⃣ Build iOS app (no code signing)
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 7️⃣ Upload iOS build artifact
      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos/
