name: Flutter iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Remove any preinstalled Flutter
      - name: Remove preinstalled Flutter
        run: sudo rm -rf /Users/runner/hostedtoolcache/flutter

      # 3️⃣ Install Flutter 3.27.3 (includes Dart 3.9.2)
      - name: Install Flutter 3.27.3
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: false

      # 4️⃣ Check versions (must show Dart 3.9.x)
      - name: Check Flutter & Dart version
        run: |
          flutter --version
          dart --version

      # 5️⃣ Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # 6️⃣ Build iOS app without signing
      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      # 7️⃣ Upload iOS build artifact
      - name: Upload iOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-build
          path: build/ios/iphoneos/
