name: Build iOS (.ipa)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter (stable base)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      - name: Upgrade Flutter to latest master (for Dart 3.9.2+)
        run: |
          git -C "$(flutter sdk-path)" fetch origin master
          git -C "$(flutter sdk-path)" checkout master
          flutter doctor -v
          flutter --version
          dart --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS release (no codesign)
        run: flutter build ipa --no-codesign

      - name: Upload IPA artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/
